CLASS Foo
	PUBLIC PROCEDURE NEW()
	ENDPROCEDURE
	PUBLIC PROCEDURE foo(arg:ARRAY OF INTEGER)
	ENDPROCEDURE
ENDCLASS
CLASS Bar INHERITS Foo
	PUBLIC PROCEDURE NEW()
		CALL SUPER.NEW()
	ENDPROCEDURE
	PUBLIC PROCEDURE foo(arg:ARRAY[1:12] OF INTEGER)
	ENDPROCEDURE
ENDCLASS

PROCEDURE valid(BYVAL arg1: Foo)
	DECLARE ten: ARRAY[1:10] OF INTEGER
	//Foo.list accepts an array with any length
	CALL arg1.foo(ten)
ENDPROCEDURE

//oh no
CALL valid(NEW Bar())
