CLASS Func_INTEGER_INTEGER
  PUBLIC PROCEDURE NEW(); ENDPROCEDURE
  PUBLIC FUNCTION get(x: INTEGER) RETURNS INTEGER
    DECLARE unimplemented: ARRAY[0:1] OF INTEGER
    RETURN unimplemented["Error: Method not implemented"]
  ENDFUNCTION
ENDCLASS

CLASS times_two INHERITS Func_INTEGER_INTEGER
  PUBLIC FUNCTION get(x: INTEGER) RETURNS INTEGER
    RETURN x * 2
  ENDFUNCTION
ENDCLASS
CLASS plus_one INHERITS Func_INTEGER_INTEGER
  PUBLIC FUNCTION get(x: INTEGER) RETURNS INTEGER
    RETURN x + 1
  ENDFUNCTION
ENDCLASS

PROCEDURE apply_twice(func: Func_INTEGER_INTEGER, x: INTEGER)
  OUTPUT func.get(func.get(x))
ENDPROCEDURE
CALL apply_twice(NEW times_two(), 5) //20
CALL apply_twice(NEW plus_one(), 5) //7

