CLASS Animal
	PUBLIC Name: STRING
	PUBLIC PROCEDURE NEW(name: STRING)
		Name <- name
	ENDPROCEDURE
	PUBLIC FUNCTION isAnimal() RETURNS BOOLEAN
		RETURN TRUE
	ENDFUNCTION
ENDCLASS
CLASS Dog INHERITS Animal
	PUBLIC PROCEDURE NEW(name: STRING)
	ENDPROCEDURE
	PUBLIC FUNCTION isAnimal() RETURNS BOOLEAN
		RETURN FALSE
	ENDFUNCTION
ENDCLASS

DECLARE animal: Animal
animal <- NEW Animal("doggy")
DECLARE dog: Animal
dog <- NEW Dog("doggy")
OUTPUT animal.isAnimal()
OUTPUT dog.isAnimal()
//CALL dog.bark()